name: auzure-deployment
jobs:
  buildandpush:
    runs-on: ubuntu-latest
    env: 
      credentials: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_CLIENT_ID: ${{ fromJSON(secrets.AZURE_CREDENTIALS)['vClientID'] }}
      AZURE_CLIENT_SECRET: ${{ fromJSON(secrets.AZURE_CREDENTIALS)['vClientSecret'] }}
      AZURE_TENANT_ID: ${{ fromJSON(secrets.AZURE_CREDENTIALS)['vTenantID'] }}
    - uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
          az account list
