
# File: .github/workflows/workflow.yml

on: [push]

jobs:
 Get-AKV-Secret:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
    - uses: actions/checkout@master
    - uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} 
    - uses: Azure/get-keyvault-secrets@v1
      with:
        keyvault: "demo343"
        secrets: 'vClientID'  # comma separated list of secret keys that need to be fetched from the Key Vault 
      id: myGetSecretAction
        
